version: "3"

services:

  node0:
    build: .
    image: powcoin
    ports:
        - "5000:5000"
    environment:
      PEERS: 'node1,node2'
      ID: 0

  node1:
    image: powcoin
    ports:
        - "5001:5000"
    environment:
      #PEERS: 'node0,node2'
      PEERS: 'node0'
      ID: 1

  node2:
    image: powcoin
    ports:
        - "5002:5000"
    environment:
      #PEERS: 'node0,node1'
      PEERS: 'node0'
      ID: 2

