version: "3"

services:

  node0:
    build: .
    image: blockcoin
    ports:
        - "5000:5000"
    environment:
      PEERS: 'node1,node2'
      BANK_ID: 0

  node1:
    image: blockcoin
    ports:
        - "5001:5000"
    environment:
      PEERS: 'node0,node2'
      BANK_ID: 1

  node2:
    image: blockcoin
    ports:
        - "5002:5000"
    environment:
      PEERS: 'node0,node1'
      BANK_ID: 2

